include ':preferencefragment_ex'
include ':viewpager_ex2'
include ':doublefragment_ex'
include ':singlefragment_ex'
include ':playmusic_service'
include ':mission'
include ':menu_ex'
include ':dialog_ex'
include ':keyboardcontrol_ex'
include ':notification_ex'
include ':systembroadcastreciever_ex'
include ':broadcastreciver_sms'
include ':broadcastreceiver_ex'
include ':bindservice'
include ':intent_service_ex'
include ':music_service'
include ':service_ex'
include ':viewpager_ex'
include ':app'
rootProject.name = "Chap11"