include ':navigationdrawer_ex'
include ':bottomsheet_ex'
include ':appbarlayout_ex'
include ':recycler_stagger'
include ':recycler_realm'
include ':recycler_cardview'
include ':recyclerview_ex'
include ':selfchk'
include ':listview_viewclass_Singer'
include ':listview_simpleadapter'
include ':listview_arrayadapter'
include ':app'
rootProject.name = "Chap13"